import {
  File,
  FileCode,
  FileImage,
  FileJson,
  FileText,
  FileType,
  Image,
  Music,
  Package,
  Settings,
  Video,
} from 'lucide-react';

const fileIconMap: Record<string, {icon: typeof File; color: string;}> = {
  '.ts': {icon: FileCode, color: 'text-blue-400'},
  '.tsx': {icon: FileCode, color: 'text-blue-400'},
  '.js': {icon: FileCode, color: 'text-yellow-400'},
  '.jsx': {icon: FileCode, color: 'text-yellow-400'},
  '.mjs': {icon: FileCode, color: 'text-yellow-400'},
  '.cjs': {icon: FileCode, color: 'text-yellow-400'},
  '.py': {icon: FileCode, color: 'text-green-400'},
  '.rb': {icon: FileCode, color: 'text-red-400'},
  '.go': {icon: FileCode, color: 'text-cyan-400'},
  '.rs': {icon: FileCode, color: 'text-orange-400'},
  '.java': {icon: FileCode, color: 'text-orange-400'},
  '.kt': {icon: FileCode, color: 'text-purple-400'},
  '.swift': {icon: FileCode, color: 'text-orange-400'},
  '.c': {icon: FileCode, color: 'text-blue-300'},
  '.cpp': {icon: FileCode, color: 'text-blue-300'},
  '.h': {icon: FileCode, color: 'text-purple-300'},
  '.cs': {icon: FileCode, color: 'text-green-400'},
  '.php': {icon: FileCode, color: 'text-indigo-400'},
  '.vue': {icon: FileCode, color: 'text-emerald-400'},
  '.svelte': {icon: FileCode, color: 'text-orange-400'},
  '.css': {icon: FileCode, color: 'text-blue-400'},
  '.scss': {icon: FileCode, color: 'text-pink-400'},
  '.less': {icon: FileCode, color: 'text-indigo-400'},
  '.html': {icon: FileCode, color: 'text-orange-400'},
  '.xml': {icon: FileCode, color: 'text-orange-300'},
  '.sh': {icon: FileCode, color: 'text-green-300'},
  '.bash': {icon: FileCode, color: 'text-green-300'},
  '.zsh': {icon: FileCode, color: 'text-green-300'},
  '.sql': {icon: FileCode, color: 'text-yellow-300'},
  '.json': {icon: FileJson, color: 'text-yellow-400'},
  '.jsonc': {icon: FileJson, color: 'text-yellow-400'},
  '.md': {icon: FileText, color: 'text-blue-300'},
  '.mdx': {icon: FileText, color: 'text-blue-300'},
  '.txt': {icon: FileText, color: 'text-vscode-text-muted'},
  '.log': {icon: FileText, color: 'text-vscode-text-muted'},
  '.csv': {icon: FileText, color: 'text-green-300'},
  '.yml': {icon: Settings, color: 'text-purple-300'},
  '.yaml': {icon: Settings, color: 'text-purple-300'},
  '.toml': {icon: Settings, color: 'text-gray-400'},
  '.ini': {icon: Settings, color: 'text-gray-400'},
  '.env': {icon: Settings, color: 'text-yellow-300'},
  '.png': {icon: FileImage, color: 'text-green-400'},
  '.jpg': {icon: FileImage, color: 'text-green-400'},
  '.jpeg': {icon: FileImage, color: 'text-green-400'},
  '.gif': {icon: FileImage, color: 'text-green-400'},
  '.webp': {icon: FileImage, color: 'text-green-400'},
  '.svg': {icon: Image, color: 'text-yellow-400'},
  '.ico': {icon: FileImage, color: 'text-green-400'},
  '.bmp': {icon: FileImage, color: 'text-green-400'},
  '.mp4': {icon: Video, color: 'text-pink-400'},
  '.mov': {icon: Video, color: 'text-pink-400'},
  '.avi': {icon: Video, color: 'text-pink-400'},
  '.webm': {icon: Video, color: 'text-pink-400'},
  '.mp3': {icon: Music, color: 'text-pink-300'},
  '.wav': {icon: Music, color: 'text-pink-300'},
  '.flac': {icon: Music, color: 'text-pink-300'},
  '.pdf': {icon: FileText, color: 'text-red-400'},
  '.doc': {icon: FileText, color: 'text-blue-400'},
  '.docx': {icon: FileText, color: 'text-blue-400'},
  '.xls': {icon: FileText, color: 'text-green-400'},
  '.xlsx': {icon: FileText, color: 'text-green-400'},
  '.pptx': {icon: FileText, color: 'text-orange-400'},
  '.zip': {icon: Package, color: 'text-yellow-300'},
  '.tar': {icon: Package, color: 'text-yellow-300'},
  '.gz': {icon: Package, color: 'text-yellow-300'},
  '.rar': {icon: Package, color: 'text-yellow-300'},
  '.7z': {icon: Package, color: 'text-yellow-300'},
  '.woff': {icon: FileType, color: 'text-red-300'},
  '.woff2': {icon: FileType, color: 'text-red-300'},
  '.ttf': {icon: FileType, color: 'text-red-300'},
  '.otf': {icon: FileType, color: 'text-red-300'},
};

export function getFileIcon(name: string): {icon: typeof File; color: string;} {
  const dot = name.lastIndexOf('.');
  if (dot !== -1) {
    const ext = name.slice(dot).toLowerCase();
    const match = fileIconMap[ext];
    if (match) return match;
  }
  return {icon: File, color: 'text-vscode-text-muted'};
}
